name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: self-hosted
    
    env:
      ImageOS: ubuntu18

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
      
    - name: Complile production release
      run: MIX_ENV=prod mix release

    - name: Run server
      run: |
        MIX_ENV=prod mix compile
        PORT=4000 MIX_ENV=prod elixir --erl "-detached" -S mix phx.server
