name: ret
on:
  push:
    branches: [ developers/lonycell/master ]
    paths-ignore: ["README.md"]

  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: lonycell/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      registry: mozillareality
      dockerfile: TurkeyDockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
